version: '3'
services:
  app:
    environment:
      # This variable is required to run local setup on Linux, determines the switch from root to user
      - LOCAL=true
    volumes:
      # Mount source instead of copy
      - ./src:/var/www/public:cached
      # PHP configuration mount
      - ./deploy/shared/conf/php/php.ini:/usr/local/etc/php/php.ini
      # PHP FPM pool settings
      - ./deploy/shared/conf/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      # Uncomment to use custom configuration with -debug image
      - ./deploy/shared/conf/xdebug/xdebug-config.ini:/usr/local/etc/php/conf.d/xdebug-config.ini
      # Uncomment line below only for testing launch script without rebuild
      - ./deploy/start.sh:/start.sh
  nginx:
    volumes:
      - ./src:/var/www/public:cached
    networks:
    - default
  redis:
    ports:
      - ${REDIS_PORT}:6379
  kibana:
    image: docker.elastic.co/kibana/kibana:${ELASTICSEARCH_VERSION}
    restart: on-failure:5
    environment:
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - default
