version: '3'
services:
  nginx:
    volumes:
      - ./deploy/frontend/conf/nginx/cache-router.conf:/etc/nginx/conf.d/cache-router.conf
    links:
      - frontend
  frontend:
    image: registry.kube.indvp.com/scandipwa-oss/frontend:${PROJECT_TAG}
    build:
      context: build/frontend
      args:
        - BASEPATH=${BASEPATH}
        - NODEJS_VERSION=${NODEJS_VERSION}
    volumes:
      - ./src/app/design/frontend/Scandiweb/pwa:/var/www/public/app/design/frontend/Scandiweb/pwa
      - ./src/vendor/scandipwa/source:/var/www/public/vendor/scandipwa/source
    working_dir: "/var/www/public/app/design/frontend/Scandiweb/pwa/"
    env_file: .env
    expose:
      - 3003
